language: generic 
sudo: required
services:
    - docker

before install:
    - docker build -t tigertond/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tigertond/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-062542055733"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
